% Ajuste de curva para obter GL
% Utilizar Matlab Curve Fitting Toolbox
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: y
%      Weights : p
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 04-Aug-2023 08:37:45

x = [200.0000  279.9082  320.2067  340.5281  399.7704  480.3674  560.2755  600.2296  640.1837  700.4592  720.0918 740.4133  760.0459  779.6785  790.0115  800.0000]';
y = [1.0000    0.9781    0.9663    0.9603    0.9429    0.9196    0.8999    0.8920    0.8848    0.8746    0.8717 0.8681    0.8648    0.8615    0.8595    0.8582]';
p = [10     1     1     1     1     1     1     1     1     1     1     1     1     1     1     5]';

%% Fit: 'untitled fit 1'.
[xData, yData, weights] = prepareCurveData( x, y, p );

% Set up fittype and options.
ft = fittype( 'poly3' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Weights = weights;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'y vs. x with p', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'x', 'Interpreter', 'none' );
ylabel( 'y', 'Interpreter', 'none' );
grid on


