%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \\vboxsvr\carloska\programas\nbr5422\veraoDia.csv
%
% Auto-generated by MATLAB on 10-Nov-2022 06:01:10

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Data", "Hora", "TAmbienteC", "VelVentoms", "DirVento", "TempCondutorC", "Corrente", "RadiacaoGlobal"];
opts.VariableTypes = ["char", "char", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Data", "Hora"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Data", "Hora"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, ["TAmbienteC", "VelVentoms", "DirVento", "TempCondutorC", "Corrente", "RadiacaoGlobal"], "DecimalSeparator", ",");
opts = setvaropts(opts, ["TAmbienteC", "VelVentoms", "DirVento", "TempCondutorC", "Corrente", "RadiacaoGlobal"], "ThousandsSeparator", ".");

% Import the data
veraoDia = readtable("../veraoDia.csv", opts);

%% Convert to output type
veraoDia = table2cell(veraoDia);
numIdx = cellfun(@(x) ~isnan(str2double(x)), veraoDia);
veraoDia(numIdx) = cellfun(@(x) {str2double(x)}, veraoDia(numIdx));

%% Clear temporary variables
clear opts